project:
  type: website
  output-dir: docs
  resources: 
    - images/

website:
  title: "Dan Yavorsky"
  favicon: /images/favicon.ico
  navbar:
    background: "#536878"
    left:
      - href: index.qmd
        text: About
      - href: cv/index.qmd
        text: CV
      - teaching.qmd
      - publications.qmd
      - href: mrci.qmd
        text: MR & CI
      - href: dcms-r.danyavorsky.com
        text: R-DCMS
      - lit.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: true



