project:
  type: website
  output-dir: docs
  resources: 
    - images/
    - CNAME

website:
  title: "Dan Yavorsky"
  description: "Quantitative Marketing Research Scientist"
  
  site-url: "https://www.danyavorsky.com"
  favicon: /images/favicon.ico
  
  navbar:
    background: "#536878"
    search: false
    left:
      - href: index.qmd
        text: "About"
      - href: cv/index.qmd
        text: CV
      - href: teaching/index.qmd
        text: Teaching
      - href: pubs/index.qmd
        text: Pubs
      - href: posts/index.qmd
        text: Posts
      - href: http://dcms-r.danyavorsky.com
        text: DCMS-R
      - href: links/index.qmd
        text: Links
  
  repo-branch: main
  repo-url: "https://github.com/dyavorsky/quarto_website"
  
format:
  html:
    theme: [cosmo, custom.scss]
    css: custom.scss
    toc: true



