project:
  type: website
  output-dir: docs

website:
  title: "DanYav"
  navbar:
    background: "#536878"
    left:
      - href: index.qmd
        text: About
      - teaching.qmd
      - publications.qmd
      - href: mrci.qmd
        text: MR & CI

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



