project:
  type: website
  output-dir: docs
<<<<<<< HEAD
  resources: images/
=======
  resources: images
>>>>>>> 2a5bafee03a9f8123b274791567eb6968e38a810

website:
  title: "DanYav"
  navbar:
    background: "#536878"
    left:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - research.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



