---
title: "Things I've Read"
---

-----

## R & Friends

#### R Programming

 - [Big Book of R](https://www.bigbookofr.com/) compiled by Oscar Baruffa
 - [R for Data Science](https://r4ds.hadley.nz/) by Hadley Wickham and Garrett Grolemund
 - [Advanced R](https://adv-r.hadley.nz/) by Hadley Wickham
 - [Adavned R Solutions](https://advanced-r-solutions.rbind.io/) by Malte Grosser and Henning Bumann
 - [ggplot2](https://ggplot2-book.org/) by Hadley Wickham
 - [R Packages](https://r-pkgs.org/) by Hadley Wickham and Jenny Bryan
 
#### Git

 - [Pro Git](https://git-scm.com/book/en/v2) by Scott Chacon and Ben Straub
 - [Happy Git and GitHub for the UserR](https://happygitwithr.com/) by Jenny Bryan
 - [Git in Practice](https://www.manning.com/books/git-in-practice) by Mike McQuaid

#### Vim

 - [OpenVim](https://www.openvim.com/) by Henrik Huttunen
 - [Mastering the Vim Language](https://www.youtube.com/watch?v=wlR5gYd6um0) recorded presentation by Chris Toomey
 - [Vim as Your Editor](https://www.youtube.com/watch?v=X6AR2RMB5tE&list=PLm323Lc7iSW_wuxqmKx_xxNtJC_hJbQ7R) a 6-part playist by ThePrimeagen

-----

## Less Academic 

#### On Life

 - [This is Water](https://web.ics.purdue.edu/~drkelly/DFWKenyonAddress2005.pdf) by David Foster Wallace
 - [A Mathematician's Lament](http://worrydream.com/refs/Lockhart-MathematiciansLament.pdf) by Paul Lockhart
 - [Teaching Smart People How to Learn](https://hbr.org/1991/05/teaching-smart-people-how-to-learn) by Chris Argyris

#### On Writing

 - [How to Send and Reply to email](https://matt.might.net/articles/how-to-email/) by Matt Might
 - [Publication, Publication](https://gking.harvard.edu/sites/scholar.harvard.edu/files/gking/files/paperspub.pdf) by Gary King

#### On Getting a PhD (in Econ or Marketing)

 - Ken Wilbur: [Reasons to Get (or Not) a PhD](https://kennethcwilbur.github.io/website//#:~:text=Reasons%20to%20get%20or%20not%20get%20a%20Ph.D.) and [Choosing a field, Subfield, and PhD Program](https://kennethcwilbur.github.io/website//#:~:text=Choosing%20a%20field%2C%20subfield%20and%20Ph.D.%20program)
 - Susan Athey: [Professional Advice](https://gsb-faculty.stanford.edu/susan-athey/professional-advice/)
 - Jesse Shapiro: [Notes on Applying for a PhD in Economics](https://scholar.harvard.edu/files/shapiro/files/phdnotes.pdf)


-----


## More Academic

#### Demand Estimation

 - Berry (1994) Estimating Discrete Choice Models of Product Differentiation [[link](https://www.jstor.org/stable/2555829)]
 - Nevo (2000) A Practitioner’s Guide to Estimation of Random-Coefcients Logit Models of Demand [[link](https://bpb-us-w2.wpmucdn.com/web.sas.upenn.edu/dist/3/499/files/2018/09/RAs_guide-1cnwy2p.pdf)]
 - Chintagunta & Nair (2011) Discrete Choice Models of Consumer Demand in Marketing [[link](https://pubsonline.informs.org/doi/10.1287/mksc.1110.0674)]
 - Berry and Haile (2021) Foundations of Demand Estimation [[link](https://www.sciencedirect.com/science/article/abs/pii/S1573448X21000017)]
 - Gandhi & Nevo (2021) Empirical Models of Demand and Supply in Differentiated Products Industries [[link](https://www.sciencedirect.com/science/article/abs/pii/S1573448X21000029)]
 - Ursu, Seiler, & Honka (Draft) The Sequential Search Model: A Framework for Empirical Research [[link](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4357557)]
 
#### Causal Inference

 - Rossi (2014) Even the Rich Can Make Themselves Poor: A Critical Examination of IV Methods in Marketing Applications [[link](https://pubsonline.informs.org/doi/10.1287/mksc.2014.0860)]
 - Angrist (2022) Empirical Strategies in Economics: Illuminating the Path From Cause to Effect [[link](https://onlinelibrary.wiley.com/doi/abs/10.3982/ECTA20640)]
 - Heckman and Pinto (Draft) Causality and Econometrics [[link](https://www.nber.org/papers/w29787)]


