---
title: "Quarto Website"
description: "How to use Quarto to create a website and host it on GitHub"
number-sections: true
draft: true
---

# Create a website template in a new directory

Suppose you are in the directory [mystuff]{.red} and you would like to create a sub-directory [mywebsite]{.red} to hold the website files. Do the following

::: panel-tabset

## RStudio

Select [Projects > New Project > New Directory > Quarto Website]{.red}

Browse to the current [mystuff]{.red} directory and input the name of the to-be-created sub-directory as [mywebsite]{.red}

For now, uncheck the boxes for Git, renv, and the Visual Editor, the click "Create Project"

## Terminal

Use the `cd` command to navigate to the [mystuff]{.red} directory and run the following:

`quarto create project website mywebsite`
:::

You should now have a new directory called [mywebsite]{.red} with the following template files:

 - [_quarto.yml]{.red}
 - [index.qmd]{.red} and [about.qmd]{.red}
 - [style.css]{.red}
 - and possibly also a [.Rproj]{.red} file and a related [.Rproj.user]{.red} hidden directory



# Render the template website

::: panel-tabset

## RStudio

RStudio should now have a [Build]{.red} tab in the top right pane next to the Environment and History tabs. 

Click on the [Build]{.red} tab and then click on the [Render Website]{.red} button.

## Terminal

With the working directory set to the [mystuff]{.red} directory, run:

`quarto preview mywebsite`

Alternative, with the working directory set to the [mywebsite]{.red} directory, run:

`quarto preview`
:::

This converts the "source" documents (.qmd and .yml files) to rendered (ie, output) HTML files. The rendered files are stored in a new sub-directory called [_source]{.red} within the [mywebsite]{.red} directory. By default, the rendered HTML files will open in a new tab of your default browser or in the [Viewer]{.red} pane of RStudio.




