---
title: "An Incomplete Collection"
toc-depth: 4
---



## (Re-)Reading List

#### On Life

 - [This is Water](https://web.ics.purdue.edu/~drkelly/DFWKenyonAddress2005.pdf) by David Foster Wallace
 - [A Mathematician's Lament](http://worrydream.com/refs/Lockhart-MathematiciansLament.pdf) by Paul Lockhart
 - [Maker's Schedule, Manager's Schedule](https://www.paulgraham.com/makersschedule.html) by Paul Graham
 - [Lesson's from Amazon](https://www.linkedin.com/posts/scarletink_12-things-i-learned-in-big-tech-activity-7032114623050891264-liMq) by David Anderson

#### On Writing

 - [How to Send and Reply to email](https://matt.might.net/articles/how-to-email/) by Matt Might
 - [Publication, Publication](https://gking.harvard.edu/sites/scholar.harvard.edu/files/gking/files/paperspub.pdf) by Gary King

#### On Learning How to Learn

 - [Teaching Smart People How to Learn](https://hbr.org/1991/05/teaching-smart-people-how-to-learn) by Chris Argyris
 - [Why Books Don't Work](https://andymatuschak.org/books/) by Andy Matuschak
 - [Evergreen Notes](https://notes.andymatuschak.org/About_these_notes?stackedNotes=z5E5QawiXCMbtNtupvxeoEX) by Andy Matuschak

#### On Getting a PhD (in Econ or Marketing)

 - Ken Wilbur: [Reasons to Get (or Not) a PhD](https://kennethcwilbur.github.io/website//#:~:text=Reasons%20to%20get%20or%20not%20get%20a%20Ph.D.) and [Choosing a field, Subfield, and PhD Program](https://kennethcwilbur.github.io/website//#:~:text=Choosing%20a%20field%2C%20subfield%20and%20Ph.D.%20program)
 - Susan Athey: [Professional Advice](https://gsb-faculty.stanford.edu/susan-athey/professional-advice/)
 - Jesse Shapiro: [Notes on Applying for a PhD in Economics](https://scholar.harvard.edu/files/shapiro/files/phdnotes.pdf)
 - Anatoli Colicev: [The PhD Journey](https://drive.google.com/file/d/1G9VsH4hbBhrtrJ7Cp4XsxuXLKuSFRjcn/view)
 - Martin Schwartz: [The Importance of Stupidity in Scientific Research](https://web.stanford.edu/~fukamit/schwartz-2008.pdf)




## Blogs

#### Stats

 - [Andrew Gelman](https://statmodeling.stat.columbia.edu/)
 - [Richard McElreath](https://elevanth.org/)
 - [Cosma Shalizi](https://www.stat.cmu.edu/~cshalizi/)

#### Data Science

 - [InstaCart](https://tech.instacart.com/)
 - [Netflix](https://netflixtechblog.com/)
 - [Airbnb](https://medium.com/airbnb-engineering)
 - [Amazon Science](https://www.amazon.science/)

#### Economics, Marketing, Consulting

 - [Joel Cadwell](https://joelcadwell.blogspot.com/) (inactive)
 - [Chris Chapman's QuantUX](https://quantuxblog.com/)
 - [John Cook](https://www.johndcook.com/blog/)
 - [Marc and Jeff Dotson](https://occasionaldivergences.com/)
 - [Andrew Heiss](https://www.andrewheiss.com/blog/)
 - [Stephan Seiler's Annual Best-of](https://www.seilerstephan.com/blog)]




## R Resources

#### R-Language

 - [Big Book of R](https://www.bigbookofr.com/) compiled by Oscar Baruffa
 - [Advanced R](https://adv-r.hadley.nz/) by Hadley Wickham
 - [Advanced R Solutions](https://advanced-r-solutions.rbind.io/) by Malte Grosser and Henning Bumann
 - [R Packages](https://r-pkgs.org/) by Hadley Wickham and Jenny Bryan
 - [R for the Rest of Us: A Stats-Free Intro](https://book.rfortherestofus.com/) by David Keyes
 - [Mastering Software Development in R](https://leanpub.com/msdr) by Roger Peng, Sean Kross, and Brooke Anderson
 - [Scaling Up with R and Arrow](https://arrowrbook.com/) by Nic Crane, Jonathan Keane, and Neal Richardson

#### Data Viz with R

 - [ggplot2](https://ggplot2-book.org/) by Hadley Wickham
 - [Data Visualization: A Practical Introduction](https://socviz.co/) by Kieran Healy
 - [Modern Data Visualization with R](https://rkabacoff.github.io/datavis/) by Robert Kabacoff

#### Stats with R 

 - [R for Data Science](https://r4ds.hadley.nz/) by Hadley Wickham and Garrett Grolemund
 - [Modern R with the Tidyverse](https://modern-rstats.eu/) by Bruno Rodrigues
 - [Tidy Modeling with R](https://www.tmwr.org/) by Max Kuhn and Julia Silge
 - [Data Analysis in R](https://bookdown.org/steve_midway/DAR/) by Steve Midway
 - [Introduction to Econometrics with R](https://www.econometrics-with-r.org/index.html) by Christoph Hanck and others
 - [Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/) by Benjamin Baumer, Daniel Kaplan, and Nicholas Horton

#### Reporting with R

 - [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) by Yihui Xie, JJ Allaire, and Garrett Grolemund
 - [Building reproducible analytical pipelines with R](https://raps-with-r.dev/) by Bruno Rodrigues
 - [Telling Stories with Data](https://tellingstorieswithdata.com/) by Rohan Alexander

 


## Technical Resources

#### Git 

 - [Pro Git](https://git-scm.com/book/en/v2) by Scott Chacon and Ben Straub
 - [Happy Git and GitHub for the UserR](https://happygitwithr.com/) by Jenny Bryan
 - [Git in Practice](https://www.manning.com/books/git-in-practice) by Mike McQuaid

#### Vim 

 - [OpenVim](https://www.openvim.com/) by Henrik Huttunen
 - [Mastering the Vim Language](https://www.youtube.com/watch?v=wlR5gYd6um0) recorded presentation by Chris Toomey
 - [Vim as Your Editor](https://www.youtube.com/watch?v=X6AR2RMB5tE&list=PLm323Lc7iSW_wuxqmKx_xxNtJC_hJbQ7R) a 6-part playist by ThePrimeagen

#### Quarto

 - [Quarto Docs](https://quarto.org/)
 - [Quarto Cheatsheet](https://rstudio.github.io/cheatsheets/html/quarto.html)
 - [Quarto Extensions](https://m.canouil.dev/quarto-extensions/)
 - Quarto website examples: [Twitter List](https://x.com/NeuroKaiii/status/1644854726498963456) [Linkedin List](https://www.linkedin.com/feed/update/urn:li:activity:7197152805483102208/)

#### Command Line / DevOps

 - [Data Science at the Command Line](https://jeroenjanssens.com/dsatcl/) by Jeroen Janssens
 - [The Unix Workbench](https://seankross.com/the-unix-workbench/) by Sean Kross
 - [Dev Ops for Data Science](https://do4ds.com) by Alex Gold
 - [Stat447: Data Science Programming Methods](https://stat447.com/) by Dirk Eddelbuettel 

#### Python

 - [Python 4 Data Science](https://aeturrell.github.io/python4DS/welcome.html#) by Arthur Turrell and others

#### Econometrics, Data Science, Machine Learning, Bayesian Stats

 - [Statistical Rethinking 2 with rstan and the tidyverse](https://solomon.quarto.pub/sr2rstan/) by Solomon Kurz
 - [Teaching Bayesian Statistics](http://talmo.uk/2024/teachingbayesian.html) by TALMO
 - [A Collection of Econometrics Resources](https://giuseppecavaliere.wixsite.com/giuseppe/econometrics-lecture-notes-and-books) by Giuseepe Cavaliere
 - [Applied Machine Learning for Tabular Data](https://aml4td.org/) by Max Kuhn and Kjell Johnson
 - [Statistical Tools for Causal Inference](https://chabefer.github.io/STCI/index.html) by Sylvain Chabe-Ferret
 - [Causal Inference: The Mixtape](https://mixtape.scunning.com/) by Scott Cunningham
 - [Applied Causal Inference Powered by ML and AI](https://causalml-book.org/) by Chernozhukov, Hansen, Kallus, Spindler, and Syrgkanis
 - [The Data Science Handbooks: Advice and Insights from 25 Amazing Data Scientists](https://www.thedatasciencehandbook.com/) by Shan, Wang, Chen, and Song

#### Notes

 - [Hierarchical Modeling](https://betanalpha.github.io/assets/case_studies/hierarchical_modeling.html) by Michael Betancourt
 - [Keep Calm and Learn Multilevel Logistic Modeling](https://rips-irsp.com/articles/10.5334/irsp.90#ill-show-you-a-three-step-simplified-procedure-for-multilevel-logistic-regression) by Nicolas Sommet and Davide Morselli
 - [Math-Stat Course Notes](https://people.stat.sc.edu/Tebbs/) by Joshua Tebbs
 - [Notes](https://www.adamnsmith.com/notes.html) by Adam N Smith
 - [Econometrics Notes](https://tbarmstr.github.io/teaching.html) by Tim Armstrong

<!--  

#### Demand Estimation

 - Berry (1994) Estimating Discrete Choice Models of Product Differentiation [[link](https://www.jstor.org/stable/2555829)]
 - Nevo (2000) A Practitioner’s Guide to Estimation of Random-Coefcients Logit Models of Demand [[link](https://bpb-us-w2.wpmucdn.com/web.sas.upenn.edu/dist/3/499/files/2018/09/RAs_guide-1cnwy2p.pdf)]
 - Chintagunta & Nair (2011) Discrete Choice Models of Consumer Demand in Marketing [[link](https://pubsonline.informs.org/doi/10.1287/mksc.1110.0674)]
 - Berry and Haile (2021) Foundations of Demand Estimation [[link](https://www.sciencedirect.com/science/article/abs/pii/S1573448X21000017)]
 - Gandhi & Nevo (2021) Empirical Models of Demand and Supply in Differentiated Products Industries [[link](https://www.sciencedirect.com/science/article/abs/pii/S1573448X21000029)]
 - Ursu, Seiler, & Honka (Draft) The Sequential Search Model: A Framework for Empirical Research [[link](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4357557)]
 
#### Causal Inference

 - Rossi (2014) Even the Rich Can Make Themselves Poor: A Critical Examination of IV Methods in Marketing Applications [[link](https://pubsonline.informs.org/doi/10.1287/mksc.2014.0860)]
 - Angrist (2022) Empirical Strategies in Economics: Illuminating the Path From Cause to Effect [[link](https://onlinelibrary.wiley.com/doi/abs/10.3982/ECTA20640)]
 - Heckman and Pinto (Draft) Causality and Econometrics [[link](https://www.nber.org/papers/w29787)]

-->



## Quotes


#### Ira Glass: Good Taste & Volume of Work ([link](https://www.youtube.com/watch?v=X2wLP0izeJE))

> Nobody tells this to people who are beginners, I wish someone told me. 
>
> All of us who do creative work, we get into it because we have good taste. But there is this gap. For the first couple years you make stuff, it’s just not that good. It’s trying to be good, it has potential, but it’s not. But your taste, the thing that got you into the game, is still killer. And your taste is why your work disappoints you. 
>
> A lot of people never get past this phase, they quit. Most people I know who do interesting, creative work went through years of this. We know our work doesn’t have this special thing that we want it to have. We all go through this. And if you are just starting out or you are still in this phase, you gotta know its normal and the most important thing you can do is do a lot of work. Put yourself on a deadline so that every week you will finish one story. It is only by going through a volume of work that you will close that gap, and your work will be as good as your ambitions. And I took longer to figure out how to do this than anyone I’ve ever met. It’s gonna take awhile. It’s normal to take awhile. You’ve just gotta fight your way through.


#### Teddy Roosevelt: The Man in the Arena ([link](https://www.theodorerooseveltcenter.org/Learn-About-TR/TR-Encyclopedia/Culture-and-Society/Man-in-the-Arena.aspx))

> It is not the critic who counts; not the man who points out how the strong man stumbles, or where the doer of deeds could have done them better. 
>
> The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood; who strives valiantly; who errs, who comes short again and again, because there is no effort without error and shortcoming; but who does actually strive to do the deeds; who knows the great enthusiasms, the great devotions; who spends himself in a worthy cause; who at the best knows in the end the triumph of high achievement, and who at the worst, if he fails, at least fails while daring greatly, so that his place shall never be with those cold and timid souls who neither know victory nor defeat.



